### ISSUE TITLE
amilys/embyserver

### ISSUE THREAD

**Issue by htyjswf** [zzsrv/Docker#1]
docker pull amilys/embyserver

**Comment by zzsrv** [comment]
registry.cn-hangzhou.aliyuncs.com/zzsrv/embyserver:latest

**Comment by htyjswf** [comment]
> registry.cn-hangzhou.aliyuncs.com/zzsrv/embyserver:latest
要改个名字吧

现在不是与lovechen/embyserver:latest  重名了嘛

**Comment by zzsrv** [comment]
> > registry.cn-hangzhou.aliyuncs.com/zzsrv/embyserver:latest
> > 要改个名字吧
> 
> 现在不是与lovechen/embyserver:latest 重名了嘛

确实，没注意之前有过一个名字了，不过不阿里云仓库不支持这种再建一级目录的形式，新地址改为：
registry.cn-hangzhou.aliyuncs.com/zzsrv/embyserver-amilys:latest

**Comment by zzsrv** [comment]
> > > registry.cn-hangzhou.aliyuncs.com/zzsrv/embyserver:latest
> > > 要改个名字吧
> > 
> > 
> > 现在不是与lovechen/embyserver:latest 重名了嘛
> 
> 确实，没注意之前有过一个名字了，不过不阿里云仓库不支持这种再建一级目录的形式，新地址改为： registry.cn-hangzhou.aliyuncs.com/zzsrv/embyserver-amilys:latest

为方便统一管理，地址更新为：registry.cn-hangzhou.aliyuncs.com/zzsrv/embyserver:latest-amilys
